server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**